### ISSUE TITLE
FlutterBrotli.decompress not working for ios side

### ISSUE THREAD

**Issue by recepozturk53** [linkkader/flutter_brotli#1]
When I tried to use that method it worked for Android emulatör perfectly, but in the ios emulator or device it's not working, unfortunately. Is there any solution? I didn't find any other package for doing the same work with this FlutterBrotli.decompress

**Comment by linkkader** [comment]
Ah yes i encounter this problem when i release last version of my release my app for ios and no i don't find a solution
the c files are not correctly imported when xcode build

**Comment by recepozturk53** [comment]
I am sorry to respond back lately, it solved for me with this 

if (Platform.isIOS) {
        final codec = BrotliCodec();
        decoded = utf8.decode(codec.decode(res.bodyBytes));
      } else {
        decoded = await FlutterBrotli.decompress(res.bodyBytes);
      }
 Used es_compression: ^2.0.10 for IOS and that's all.
